### ISSUE TITLE
Google Keyboard Crash

### ISSUE THREAD

**Issue by gudenau** [PureNexusProject/android_packages_apps_Settings#3]
I'm sorry if this is not the correct repo to create an issue.

After the PureNexus update that started using the Google keyboard instead of the AOSP keyboard the keyboard settings cash. I tried clearing the data for the Google keyboard and they didn't help.

Steps to reproduce:
Open settings
Go-to language and input
Go-to Virtual Keyboard
Go-to Gboard
Go-to Preferences, Text Correction, Glide Typing, Dictionary, Search or Advanced.

What is expected to happen:
The keyboard settings to show the proper settings.

What happens:
The keyboard settings crash with the stack trace reason saying that the settings XML isn't specified.

**Comment by Jertlok** [comment]
Do you have any Substratum layer enabled?

**Comment by beanstown106** [comment]
a clean flash will fix this issue

**Comment by gudenau** [comment]
This did fix it, didn't think to try that. Sorry for the stupid problem.
